# Generated by Django 2.0.1 on 2018-01-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('origin_phone', models.CharField(max_length=11, null=True)),
                ('destination_phone', models.CharField(max_length=11, null=True)),
                ('price', models.FloatField(editable=False, null=True)),
                ('start_id', models.IntegerField(null=True)),
                ('end_id', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['started_at'],
            },
        ),
    ]
