# Generated by Django 2.0.1 on 2018-01-24 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonecalls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='destination_phone',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='call',
            old_name='origin_phone',
            new_name='source',
        ),
    ]
