# Generated by Django 2.0.1 on 2018-01-26 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonecalls', '0002_auto_20180124_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('phone', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='call',
            name='end_id',
        ),
        migrations.RemoveField(
            model_name='call',
            name='start_id',
        ),
        migrations.AlterField(
            model_name='call',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_calls', to='phonecalls.Subscriber'),
        ),
        migrations.AlterField(
            model_name='call',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_calls', to='phonecalls.Subscriber'),
        ),
    ]
